# file: roles/install-pgbouncer/tasks/configure.yml

- name: "Stage 2: create pgbouncer.ini"
  template:
    src: pgbouncer.ini.j2
    dest: "{{ pgbouncer_ini }}"
    owner: "{{ pgbouncer_admin_user }}"
    group: "{{ pgbouncer_admin_group }}"
    mode: 0600

- name: "Satge 2: add userlist.txt"
  template:
    src: userlist.txt.j2
    dest: "{{ pgbouncer_auth_file }}"
    owner: "{{ pgbouncer_admin_user }}"
    group: "{{ pgbouncer_admin_group }}"
    mode: 0600

- name: "Stage 2: prepare Systemd custom config folder"
  file:
    name: /etc/systemd/system/pgbouncer.service.d
    state: directory
    mode: 0755

- name: "Stage 2: add pgbouncer.service custom config"
  template:
    src: etc_systemd_system_pgbouncer.service.d_custom.conf.j2
    dest: /etc/systemd/system/pgbouncer.service.d/custom.conf
    owner: root
  register: pgbouncer_systemd_custom_conf

- name: "Stage 2: restart pgbouncer"
  systemd:
    name: pgbouncer
    state: restarted
    daemon_reload: yes
  when: pgbouncer_systemd_custom_conf.changed

- name: "Stage 2: start pgbouncer"
  service:
    name: pgbouncer
    state: started
    enabled: yes
